 
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddSearchEngine: typeof import('./components/AddSearchEngine.vue')['default']
    AddUrl: typeof import('./components/AddUrl.vue')['default']
    Approve: typeof import('./components/Approve.vue')['default']
    Aside: typeof import('./components/Aside.vue')['default']
    CustomTreeSelect: typeof import('./components/smallComp/CustomTreeSelect.vue')['default']
    EditEngines: typeof import('./components/EditEngines.vue')['default']
    LikeHeart: typeof import('./components/smallComp/LikeHeart.vue')['default']
    LoadingMask: typeof import('./components/LoadingMask.vue')['default']
    LoginFormComp: typeof import('./components/form/LoginFormComp.vue')['default']
    MainPanelSettings: typeof import('./components/MainPanelSettings.vue')['default']
    Notice: typeof import('./components/Notice.vue')['default']
    RegisterFormComp: typeof import('./components/form/RegisterFormComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Swiper: typeof import('./components/Swiper.vue')['default']
    'Swiper copy': typeof import('./components/Swiper copy.vue')['default']
    Time: typeof import('./components/Time.vue')['default']
    TitleDiv: typeof import('./components/TitleDiv.vue')['default']
    ToolBox: typeof import('./components/home/toolBox.vue')['default']
    UploadAudio: typeof import('./components/UploadAudio.vue')['default']
    UploadImage: typeof import('./components/UploadImage.vue')['default']
    VolumeComp: typeof import('./components/smallComp/VolumeComp.vue')['default']
  }
}
